/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#eae8e7",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ffb95e",
        "on-tertiary-fixed": "#101b30",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e4e2e1",
        "inverse-surface": "#303030",
        "outline-variant": "#e6bdb9",
        "error": "#ba1a1a",
        "tertiary": "#515c74",
        "surface-variant": "#e4e2e1",
        "on-tertiary-container": "#fefcff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "inverse-on-surface": "#f3f0f0",
        "surface": "#fbf9f8",
        "secondary-container": "#fdb24c",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb3ad",
        "on-secondary": "#ffffff",
        "secondary": "#855300",
        "on-primary-fixed": "#410004",
        "primary-fixed-dim": "#ffb3ad",
        "surface-tint": "#c0001b",
        "on-secondary-fixed": "#2a1700",
        "primary-container": "#e3212c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6a758d",
        "tertiary-fixed-dim": "#bbc6e2",
        "on-tertiary-fixed-variant": "#3c475d",
        "primary-fixed": "#ffdad7",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#930012",
        "on-surface": "#1b1c1c",
        "secondary-fixed": "#ffddb7",
        "background": "#fbf9f8",
        "on-background": "#1b1c1c",
        "on-secondary-container": "#704500",
        "surface-container": "#f0eded",
        "tertiary-fixed": "#d7e2ff",
        "outline": "#926f6c",
        "surface-bright": "#fbf9f8",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed-variant": "#653e00",
        "primary": "#bb001b",
        "on-surface-variant": "#5d3f3d"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
